name: Create Release and Zip Archive

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Zip Archive of Repository
        run: |
          zip -r quads-modest-toolbox-${{ github.event.inputs.version }}.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          body: |
            This release includes the full contents of the repository.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Zip Archive to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: quads-modest-toolbox-${{ github.event.inputs.version }}.zip
          asset_name: quads-modest-toolbox-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
