name: Create Release and Zip Archive

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean up playerlist lua
        run: |
          sed -i '/get_config_flag.*420/d' quads_toolbox_scripts/ultimate_playerlist.lua

      - name: Create Zip Archive of all script files
        run: |
          zip -r quads-modest-toolbox-${{ github.event.inputs.version }}.zip . -x ".git/*" ".github/*"

      - name: Get Previous Tag
        id: get_previous_tag
        run: echo "last_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Get Commit Messages
        id: get_commit_messages
        run: |
          commits=$(git log ${{ env.last_tag }}..HEAD --pretty=format:"* %s")
          echo 'commit_messages<<EOF' >> "$GITHUB_ENV"
          echo "$commits" >> "$GITHUB_ENV"
          echo EOF >> "$GITHUB_ENV"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          body: |
            Changes in this release:
            ${{ env.commit_messages }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

        # Step to remove the source code archives
      - name: Remove Source Code Assets
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          release_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.version }} | jq -r .id)
          assets=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/$release_id/assets | jq -r '.[] | select(.name | endswith(".zip") or endswith(".tar.gz")) | .id')
          for asset_id in $assets; do
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id
          done
          
      - name: Upload Zip Archive to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: quads-modest-toolbox-${{ github.event.inputs.version }}.zip
          asset_name: quads-modest-toolbox-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
        env:  
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          
      - name: Print Release URL
        run: echo ${{ steps.create_release.outputs.html_url }}
